### ISSUE TITLE
Cannot get TREEasy running properly...

### ISSUE THREAD

**Issue by bheimbu** [MaoYafei/TREEasy#1]
Dear Mao,

your program seems to be perfect for my project. It is also running smoothly on the Acropora data. However, once I am trying to use my own data, several errors occur: 
`rm: cannot remove ‘termites/Cluster_1/aln_seqs’: No such file or directory` and yes, of course there is no such folder from the beginning.

And also, it is giving me following errors:
`[00:00:00] Loaded alignment with 7 taxa and 912 sites
ERROR: Invalid character in sequence 1 at position 5: L
ERROR: Invalid character in sequence 1 at position 7: L`
but those parts are amino acid sequences, which do have Ls?!

I have attached my files ([Cluster1.zip](https://github.com/MaoYafei/TREEasy/files/4479872/Cluster1.zip)), please could you help me?

Cheers Bastian

**Comment by MaoYafei** [comment]
Hi Bastian,

I tried your dataset. I found the problem is that the standard genetic code table does not match your data (https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi).  I guess your nuclear sequences are invertebrates mitochondria. If I was right, the sequences can not pass the criteria of checking in the program. 

There are two options you can choose:

1. change translate() to translate(table=5) for line 38 and line 39 in ML_build.py.

2. Do not use CDS option, just use your nuclear sequence. 

Thank you. 

Best, 
Yafei

**Comment by bheimbu** [comment]
Thanks Yafei,

I will try your recommendations.


Cheers Bastian

Sent from my iPhone

On 15. Apr 2020, at 18:12, Yafei <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Bastian,

I tried your dataset. I found the problem is that the standard genetic code table does not match your data (https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi). I guess your nuclear sequences are invertebrates mitochondria. If I was right, the sequences can not pass the criteria of checking in the program.

There are two options you can choose:

  1.  change translate() to translate(table=5) for line 38 and line 39 in ML_build.py.

  2.  Do not use CDS option, just use your nuclear sequence.

Thank you.

Best,
Yafei

**Comment by bheimbu** [comment]
Dear Yafei,

the program is now running, but stops/freezes indefinitely after `Execution log saved to: /home/uni08/bheimbu/bin/TREEasy/termites/Cluster_1/CONCAT/concatenated.out_raxml_ng.raxml.log Analysis started: 16-Apr-2020 09:00:52 / finished: 16-Apr-2020 09:02:53 Elapsed time: 121.525 seconds`. 

And also I get following error: `ML tree done rm: cannot remove ‘termites/Cluster_1/all_iqtree_spename.contree’: No such file or directory sed: no input files sed: no input files`

I have used following input files ([Cluster1_Test2.zip](https://github.com/MaoYafei/TREEasy/files/4485783/Cluster1_Test2.zip)). 


Cheers Bastian

**Comment by bheimbu** [comment]
Hi Yafei,

could you please get back to me?! Might the freezing be due to the high number of included taxa?


Cheers Bastian

**Comment by MaoYafei** [comment]
> Hi Yafei,
> 
> could you please get back to me?! Might the freezing be due to the high number of included taxa?
> 
> Cheers Bastian

Hi Bastian,

I just checked your attached file, the sequences in your Fasta file do not match your species and gene name file. 

Also, based on your species name file, there are 107 samples. It could be run for species tree inference but not for network inference. Just terminate the tool after all species tree inferences done. Also, ignore the "rm" error, it won't affect the running.

Best,
Yafei

**Comment by bheimbu** [comment]
Hi Yafei,

thanks for your reply. What would be the max number of samples for network inference?

Cheers Bastian

**Comment by MaoYafei** [comment]
> Hi Yafei,
> 
> thanks for your reply. What would be the max number of samples for network inference?
> 
> Cheers Bastian

Hi Bastian,

I recommend you to see SNaQ and PhyloNet paper. Personal experience: I won't run the network when your sample size is over 15.

-Yafei
