### ISSUE TITLE
OMP: Error #34: System unable to allocate necessary resources for OMP thread:

### ISSUE THREAD

**Issue by HongboTang** [MaoYafei/TREEasy#2]
Hello, 

Nice work help us save many time to use other softs!

I have 4 species, 9000 genes, and i run this command:
python TREEasy.py -d 4pop/non_cds -s 4pop/4pop_spe_name.txt -g 4pop/4pop_gene_name.txt -b 80 -r GRCg6 -n 2 -k 4 -t 2 -c noncds;
When i run the program, i met these Errors, what should i do? 
Thank you very much!

<img width="833" alt="image" src="https://user-images.githubusercontent.com/72898813/170815345-6c3ea0ed-dc61-4455-816e-59309627d225.png">

**Comment by MaoYafei** [comment]
> Hello,
> 
> Nice work help us save many time to use other softs!
> 
> I have 4 species, 9000 genes, and i run this command: python TREEasy.py -d 4pop/non_cds -s 4pop/4pop_spe_name.txt -g 4pop/4pop_gene_name.txt -b 80 -r GRCg6 -n 2 -k 4 -t 2 -c noncds; When i run the program, i met these Errors, what should i do? Thank you very much!
> 
> <img alt="image" width="833" src="https://user-images.githubusercontent.com/72898813/170815345-6c3ea0ed-dc61-4455-816e-59309627d225.png">

Hi Hongbo,

It seems that your OMP package in python2 can not be properly running with TREEasy. 

Please run the TREEasy with the example test firstly to check that the modules are ready to use. 

Thank you.

Best,
Yafei
